services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

when@test:
  services:
    test.telegram_http_client:
      class: Symfony\Component\HttpClient\MockHttpClient
      public: true

    App\Service\TelegramSendApiService:
      arguments:
        $httpClient: '@test.telegram_http_client'
        $simulateSendFailure: false
